namespace Refresh.GameServer.Types.Telemetry;

// This represents the submodes for LBP2/3
// Vita has different submodes after 48
public enum PoppetSubMode
{
    None,
    EditVerts = 6,
    Inventory = 11,
    GrabPlan = 15,
    Photo = 16,
    Remote = 22,
    SwitchConnector,
    CameraZoneTrigger,
    CameraZoneTarget,
    CameraGlobalZoom,
    TweakObjectPlacement,
    PickEmitterObject,
    Danger,
    PickDecorations,
    FloodFill,
    MotionControllerCalibrate,
    MotionControllerNotActive,
    MotionControllerActivating,
    MotionControllerPicking,
    MotionControllerHolding,
    MotionControllerDeactivating,
    PlaceStickers,
    PlaceDecorations,
    PlaceBolt,
    LongJoint,
    DecorativeThing,
    CircuitBoard,
    StickerCutter,
    Glue,
    EditUv,
    MovePlanetBadge,
    Unphysics,
    Paint,
    Pocket,
    Grouping = 52,
    QuickPocket,
    Wash,
    LevelImporter,
    AdventureItems,
    AdventureItemsOnly,
    AdventureCharactersOnly,
    AdventureCharactersOnlySecondary,
    PickZone,
    PlaceZone,
    RailJoint,
    QuestLog,
    PickLocation,
    PickDirection,
    
    
}